name: Image runner
on:
    push
jobs:
    image-builder:
        name: Checkout prerequisites and build image
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout current repo
                uses: actions/checkout@v3
            -
                name: Use the provided Dockerfile to build an image
                run: docker build -t my_image .
            -
                name: List docker images
                run: docker images
    #run jobs separately with demonstrating image-runner
    #image_runner_merged without demonstrating image-runner, 
    image-runner:       
           name: the main job
           runs-on: ubuntu-lateset
           needs: image-builder
           steps:
           -
                name: Run the image
                run: docker run --rm -t my_image
